"""create core tables: institutions, jobs, search_runs, verification_evidence

Revision ID: 2284e01472ba
Revises: 
Create Date: 2026-04-07 22:11:03.609530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2284e01472ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

institution_type_enum = postgresql.ENUM(
    'UNIVERSITY',
    'COMPANY',
    'NONPROFIT',
    'GOVERNMENT',
    'RESEARCH_LAB',
    'OTHER',
    name='institutiontype',
    create_type=False,
)

search_run_status_enum = postgresql.ENUM(
    'INITIATED',
    'SEARCHING',
    'VERIFYING',
    'STORING',
    'COMPLETED',
    'FAILED',
    name='searchrunstatus',
    create_type=False,
)

experience_level_enum = postgresql.ENUM(
    'INTERN',
    'ENTRY',
    'MID',
    'SENIOR',
    'LEAD',
    'EXECUTIVE',
    'UNKNOWN',
    name='experiencelevel',
    create_type=False,
)

verification_check_name_enum = postgresql.ENUM(
    'URL_WELLFORMED',
    'NOT_AGGREGATOR',
    'DNS_RESOLVES',
    'HTTP_REACHABLE',
    'CONTENT_SIGNALS',
    name='verificationcheckname',
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    institution_type_enum.create(bind, checkfirst=True)
    search_run_status_enum.create(bind, checkfirst=True)
    experience_level_enum.create(bind, checkfirst=True)
    verification_check_name_enum.create(bind, checkfirst=True)

    op.create_table('institutions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('careers_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('institution_type', institution_type_enum, nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_domain'), 'institutions', ['domain'], unique=True)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_table('search_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', search_run_status_enum, nullable=False),
    sa.Column('initiated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('candidates_raw', sa.Integer(), nullable=False),
    sa.Column('candidates_verified', sa.Integer(), nullable=False),
    sa.Column('institutions_new', sa.Integer(), nullable=False),
    sa.Column('institutions_updated', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_updated', sa.Integer(), nullable=False),
    sa.Column('error_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('experience_level', experience_level_enum, nullable=True),
    sa.Column('salary_range', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('source_query', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_institution_id'), 'jobs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_index(op.f('ix_jobs_url'), 'jobs', ['url'], unique=True)
    op.create_table('verification_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('search_run_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidate_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('check_name', verification_check_name_enum, nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_evidence_search_run_id'), 'verification_evidence', ['search_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_evidence_search_run_id'), table_name='verification_evidence')
    op.drop_table('verification_evidence')
    op.drop_index(op.f('ix_jobs_url'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_institution_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('search_runs')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_domain'), table_name='institutions')
    op.drop_table('institutions')

    bind = op.get_bind()
    verification_check_name_enum.drop(bind, checkfirst=True)
    experience_level_enum.drop(bind, checkfirst=True)
    search_run_status_enum.drop(bind, checkfirst=True)
    institution_type_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
